
spring.profiles.active=local

# Configura��o SMTP para Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mourajuniorf@gmail.com
spring.mail.password=ztdi bjyk rbuk jnci
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.main.allow-circular-references=true
app.mail.enabled=true
pagbank.notification_url=http://localhost:8080/api/pagbank/notifications

# PagBank (PagSeguro) configuration
# Use sandbox while testing locally
pagbank.sandbox=true
pagbank.email=mourajuniorf@gmail.com
pagbank.token=5534938a-cb53-4fc0-bf99-2e6b7d7ea6fa8bb874844ff2883ad40381352b5585f6abed-0b99-46dd-8395-cfc5adfe47fe
pagbank.client_id=
pagbank.client_secret=
pix.key=mourajuniorf@gmail.com
